FROM grafana/grafana:11.1.1

RUN grafana cli plugins install petrslavotinek-carpetplot-panel && \
    grafana cli plugins install grafana-googlesheets-datasource && \
    grafana cli plugins install simpod-json-datasource && \
    grafana cli plugins install dalvany-image-panel && \
    grafana cli \
      --pluginUrl https://github.com/panodata/panodata-map-panel/releases/download/0.16.0/panodata-map-panel-0.16.0.zip \
      plugins install grafana-map-panel
