branch-defaults:
  docker-reporting:
    environment: safecastreporting-dev-005
global:
  application_name: reporting
  default_ec2_keyname: safecastapi
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-west-2
  workspace_type: Application
