global:
  application_name: reporting
  default_ec2_keyname: safecastdev
  default_platform: 64bit Amazon Linux 2016.09 v2.3.0 running PHP 5.6
  default_region: us-west-2
  profile: safecast
  sc: git
