version: 2.1
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - run:
       shell: /bin/sh
       command: |
          echo Running test
          mkdir -p /tmp/test-results
