version: 2.1
jobs:
  build:
    docker:
      - image: muryanto1/mycentos7:mycentos7withgit
    steps:
      - checkout
      - run: |
         echo "Hello world!"
         ./scripts/install_grafana.sh
