version: v1.0
name: Production deploy pipeline
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

blocks:
- name: Main
  task:
    secrets:
    - name: aws-dev
    env_vars:
    - name: S3_BUCKET_NAME
      value: elasticbeanstalk-us-west-2-985752656544
    - name: EB_ENV_NAME
      value: safecastrpt-prd
    - name: EB_APP_NAME
      value: reporting
    - name: AWS_DEFAULT_REGION
      value: us-west-2
    - name: CREATE_APPLICATION_VERSION
      value: "true"
    prologue:
      commands:
      - checkout
    jobs:
    - name: Deploy
      commands:
      - .elasticbeanstalk/deploy.sh
