name: Deploy same env

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment: dev/prd'
        required: true
        default: dev
      app_version:
        description: 'App version (default: most recent)'
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Safecast deployer
        run: |
          echo running safecast_deployer ${{ github.event.inputs.environment }} reporting ${{ github.event.inputs.app_version }}
