name: Main

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: ~

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and publish artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::985752656544:role/reporting-github-actions
          role-session-name: reporting-github-actions
          aws-region: us-west-2
      - name: Create application bundle
        uses: Safecast/github-actions/bundle-application@v1
        with:
            app: reporting
            s3_bucket: elasticbeanstalk-us-west-2-985752656544
